blank_issues_enabled: false
contact_links:
  - name: Codegyan support
    url: https://support.codegyan.in/
    about: |
      Please only file issues here that you believe represent actual bugs or feature requests for the Codegyan Node library.
      If you're having general trouble with the Codegyan API, please visit our help center to get support.